name: Docker Image CIMore actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:More actions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag the Docker image
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%s) Add commentMore actions
        COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-_')
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/dernier-kilometre
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:$COMMIT_MESSAGE
        
    - name: Push the Docker imageAdd commentMore actions
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%s)Add commentMore actions
        COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-_')
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/dernier-kilometre
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$COMMIT_MESSAGE
